---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  network:
    - [ "forwarded_port", { guest: 80, host: 20080 } ]
    - [ "forwarded_port", { guest: 9001, host: 29001 } ]
    - [ "forwarded_port", { guest: 9002, host: 29001 } ]
    - [ "private_network", { ip: "192.168.33.33" } ]
platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    customize:
      memory: 1536
      cpus: 2

# - name: ubuntu-10.04
#   driver_config:
#     box: opscode-ubuntu-10.04
#     box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
# - name: centos-6.4
#   driver_config:
#     box: opscode-centos-6.4
#     box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
# - name: centos-5.9
#   driver_config:
#     box: opscode-centos-5.9
#     box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box

suites:
- name: default
  run_list: [ 
    "recipe[revily::default]",
    "recipe[revily::users]",
    "recipe[revily::redis]",
    "recipe[revily::nginx]",
    "recipe[revily::postgresql]",
    "recipe[revily::ruby]",
    "recipe[revily::api]"
  ]
  attributes: {
    postgresql: {
      password: {
        postgres: "d4dd6397cf55a4507874c3864f092a8c"
      }
    }
  }
