language: ruby
rvm:
  - 1.9.3
env:
  global:
  - S3_REGION="us-east-1"
  - S3_BUCKET_NAME="revily-chef-bundle"
  - secure: "jzHHjr8Ernl4Nkwjeyj9kEmUn20J7xk0y0IKSJ+Ot/JZNTlIhXBHupCuS6PFxVqsWb3osiCpf2sKwfm+GQITN8LV3Itx1Q6twVjNcrrAHVtwOHBDbMqlCo4CSz/uvg1Swe5vwl8u2TOTV7X+G7gDxOBqOTqxpjqU8ozkAC5ZSMI="
install: "script/bootstrap"
script: "script/cibuild"
