name              "revily"
maintainer        "Applied Awesome LLC."
maintainer_email  "hi@revi.ly"
license           "Apache 2.0"
description       "Installs and configures Revily and associated services"
long_description  "Please refer to README.md"
version           "0.1.0"

recipe "revily"
recipe "revily::omnibus", "Installs omnibus version of Revily (including dependencies, PostgreSQL, Redis, etc."
recipe "revily::postgresql"
recipe "revily::redis"
recipe "revily::api"
recipe "revily::web"

depends "apt"
depends "yum"
depends "postgresql"
depends "redisio"
depends ""

supports "debian"
supports "ubuntu"
supports "suse"
supports "centos"
supports "amazon"
supports "redhat"
supports "fedora"
supports "gentoo"
supports "mac_os_x"
supports "mac_os_x_server"

# for installing on OSX, this is required for installation and compilation
suggests "homebrew"
