name              "revily"
maintainer        "Applied Awesome LLC."
maintainer_email  "hi@revi.ly"
license           "Apache 2.0"
description       "Installs and configures Revily and associated services"
long_description  "Please refer to README.md"
version           "0.1.0"

recipe "revily::default",    "default recipe"
recipe "revily::api",        "Installs Revily API service"
recipe "revily::users",      "Creates user/group for Revily service"
recipe "revily::omnibus",    "Installs omnibus version of Revily (including dependencies, PostgreSQL, Redis, etc."
recipe "revily::postgresql", "Installs and configures PostgreSQL database for Revily"
recipe "revily::redis",      "Installs and configures Redis database servers for Revily"
recipe "revily::web",        "Installs Revily Web UI"

depends "application"
depends "application_ruby"
depends "apt"
depends "git"
depends "nginx"
depends "postgresql"
depends "rbenv"
depends "redisio"
# depends "ruby_build"
depends "runit"
depends "yum"

supports "debian"
supports "ubuntu"
supports "centos"
supports "amazon"
supports "redhat"
supports "fedora"
